version: '3.7'

services:
  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - 5340:80      

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411    
    ports:
      - "6831:6831/udp"
      - "16686:16686" 
      - "9411:9411" 

  # zipkin:
  #   image: openzipkin/zipkin
  #   container_name: zipkin
  #   ports:
  #     - 9411:9411   

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq    
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"    
