apiVersion: v1
kind: ConfigMap
metadata:
  name: aspnetcore-configmap
data:
  appsettings.Kubernetes.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Database": {
        "ConnectionString": "Kubernetes ConnectionString"
      }
    }
