apiVersion: v1
kind: Secret
metadata:
  name: aspnetcore-secret
data:
  appsettings.Kubernetes.json: ICAgIHsKICAgICAgIkxvZ2dpbmciOiB7CiAgICAgICAgIkxvZ0xldmVsIjogewogICAgICAgICAgIkRlZmF1bHQiOiAiSW5mb3JtYXRpb24iLAogICAgICAgICAgIk1pY3Jvc29mdCI6ICJXYXJuaW5nIiwKICAgICAgICAgICJNaWNyb3NvZnQuSG9zdGluZy5MaWZldGltZSI6ICJJbmZvcm1hdGlvbiIKICAgICAgICB9CiAgICAgIH0sCiAgICAgICJEYXRhYmFzZSI6IHsKICAgICAgICAiQ29ubmVjdGlvblN0cmluZyI6ICJLdWJlcm5ldGVzIENvbm5lY3Rpb25TdHJpbmciCiAgICAgIH0KICAgIH0=